### ISSUE TITLE
Buy Boat

### ISSUE THREAD

**Issue by tugapower0** [esx-framework/esx_boat#15]
If a player is viewing the boat and press to buy and does not have enought money to buy recebes the notification it does not have enought money and the menu close leaving the player stucked viewing the current boat.

**Comment by tugapower0** [comment]
Too fix just remove **ESX.CloseContext()** here:

https://github.com/esx-framework/esx_boat/blob/main/client/main.lua#L71C12-L71C12

**Comment by Thekuca** [comment]
Thanks for reporting the issue! I pushed the fix.
