### ISSUE TITLE
Preview Boats

### ISSUE THREAD

**Issue by tugapower0** [esx-framework/esx_boat#16]
When you are inside the boat previewing pressing backspace or esc will close the menu living the player stuck inside boat.

**Comment by Gellipapa** [comment]
@tugapower0 Hi! Thank you for reported issue, we will fix soon.

**Comment by Gellipapa** [comment]
@tugapower0 Fixed please download latest version and test please. Thank you for reported issue.

**Comment by tugapower0** [comment]
Working perfect, thanks @Gellipapa
