### ISSUE TITLE
[Bug] when buying

### ISSUE THREAD

**Issue by NexDK** [esx-framework/esx_boat#20]
When you buy `Seashark (Dark Blue)`  then when you look in your garage then its called `Seashark (Random Color)`

![Skærmbillede 2023-10-02 054658](https://github.com/esx-framework/esx_boat/assets/36231983/98d87299-4fb6-4d6a-9e44-6ff71ebcaf8d)

When i buy the  `Seashark (Dark Blue)`

![Skærmbillede 2023-10-02 054726](https://github.com/esx-framework/esx_boat/assets/36231983/dd21cb9b-87b9-4c61-9652-ca24078d706e)

**Comment by Gellipapa** [comment]
@Arctos2win Hi! Can you tested this?

**Comment by Gellipapa** [comment]
@Arctos2win Hi! Any status?

**Comment by Gellipapa** [comment]
@NexDK Hi! Fixed please download latest version, thank you, i closed issue.
